### ISSUE TITLE
fix failing ITs in CI

### ISSUE THREAD

**Issue by jdcasey** [release-engineering/pom-manipulation-ext#178]
http://ci.commonjava.org:8080/job/pom-manipulation-ext/47/

**Comment by rnc** [comment]
In one of the failing ITs there is
```
[DEBUG] Could not find metadata org.apache.maven.plugins:maven-ear-plugin/maven-metadata.xml in local.central (file:///var/jenkins_home/jobs/pom-manipulation-ext/workspace/.repository)
[WARNING] Could not transfer metadata org.apache.maven.plugins:maven-ear-plugin/maven-metadata.xml from/to central (http://repo.maven.apache.org/maven2): repo.maven.apache.org
org.sonatype.aether.transfer.MetadataTransferException: Could not transfer metadata org.apache.maven.plugins:maven-ear-plugin/maven-metadata.xml from/to central (http://repo.maven.apache.org/maven2): repo.maven.apache.org
	at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$3.wrap(WagonRepositoryConnector.java:930)
	at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$3.wrap(WagonRepositoryConnector.java:920)
	at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$GetTask.run(WagonRepositoryConnector.java:669)
	at org.sonatype.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:60)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:662)
Caused by: org.apache.maven.wagon.TransferFailedException: repo.maven.apache.org
	at org.apache.maven.wagon.shared.http4.AbstractHttpClientWagon.fillInputData(AbstractHttpClientWagon.java:799)
	at org.apache.maven.wagon.StreamWagon.getInputStream(StreamWagon.java:116)
	at org.apache.maven.wagon.StreamWagon.getIfNewer(StreamWagon.java:88)
	at org.apache.maven.wagon.StreamWagon.get(StreamWagon.java:61)
	at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$GetTask.run(WagonRepositoryConnector.java:601)
	... 4 more
Caused by: java.net.UnknownHostException: repo.maven.apache.org
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$1.lookupAllHostAddr(InetAddress.java:876)
	at java.net.InetAddress.getAddressFromNameService(InetAddress.java:1229)
	at java.net.InetAddress.getAllByName0(InetAddress.java:1180)
	at java.net.InetAddress.getAllByName(InetAddress.java:1110)
	at java.net.InetAddress.getAllByName(InetAddress.java:1046)
	at org.apache.maven.wagon.providers.http.httpclient.impl.conn.DefaultClientConnectionOperator.resolveHostname(DefaultClientConnectionOperator.java:242)
	at org.apache.maven.wagon.providers.http.httpclient.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:130)
	at org.apache.maven.wagon.providers.http.httpclient.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:149)
	at org.apache.maven.wagon.providers.http.httpclient.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:121)
	at org.apache.maven.wagon.providers.http.httpclient.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:573)
	at org.apache.maven.wagon.providers.http.httpclient.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:425)
	at org.apache.maven.wagon.providers.http.httpclient.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:820)
	at org.apache.maven.wagon.providers.http.httpclient.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:754)
	at org.apache.maven.wagon.shared.http4.AbstractHttpClientWagon.execute(AbstractHttpClientWagon.java:674)
	at org.apache.maven.wagon.shared.http4.AbstractHttpClientWagon.fillInputData(AbstractHttpClientWagon.java:793)
	... 8 more
```

**Comment by jdcasey** [comment]
yep, seems to have been a transient problem.
