### ISSUE TITLE
Logging in CLI Integration tests

### ISSUE THREAD

**Issue by rnc** [release-engineering/pom-manipulation-ext#194]
See errors like
```
Failed to instantiate [ch.qos.logback.classic.LoggerContext]
Reported exception:
java.lang.IllegalAccessException: Only certain classes can access this method.
        at ch.qos.logback.classic.util.ContextSelectorStaticBinder.init(ContextSelectorStaticBinder.java:60)
        at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:93)
        at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
        at org.slf4j.LoggerFactory.bind(LoggerFactory.java:129)
        at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:108)
        at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:302)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:276)
        at org.eclipse.jetty.util.log.Slf4jLog.<init>(Slf4jLog.java:38)
        at org.eclipse.jetty.util.log.Slf4jLog.<init>(Slf4jLog.java:32)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at java.lang.Class.newInstance(Class.java:374)
        at org.eclipse.jetty.util.log.Log.initialized(Log.java:161)
        at org.eclipse.jetty.util.log.Log.getLogger(Log.java:435)
        at org.eclipse.jetty.util.log.Log.getLogger(Log.java:425)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.<clinit>(AbstractLifeCycle.java:33)
        at org.commonjava.maven.ext.manip.rest.MockVersionTranslator.<init>(MockVersionTranslator.java:18)
```

and

```
java.lang.IncompatibleClassChangeError: Class ch.qos.logback.classic.LoggerContext does not implement the requested interface org.slf4j.ILoggerFactory
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:277)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:288)
	at org.commonjava.maven.ext.manip.DefaultCliIntegrationTest.<init>(DefaultCliIntegrationTest.java:36)
```

**Comment by rnc** [comment]
Fixed by #196
